### ISSUE TITLE
Usable with class component?

### ISSUE THREAD

**Issue by jeanlucdu55** [CharlesStover/react-capsule#2]
Hi Charles, 

Thanks for the awesome work, we are big fan of ReactN, 

Our projects are a mix of class and function components, can we use this library inside a classic state component, if so, how? 

Thanks, 

Théo

**Comment by quisido** [comment]
It is not currently set up to support this out-of-the-box, but it is extensible for it. I am unsure what API should be "official" for it, but play around with something like this until you find something you like:

```
    componentDidMount() {
      myCapsule.subscribe(this.forceUpdate);
    }
    componentWillUnmount() {
      myCapsule.unsubscribe(this.forceUpdate);
    }
```

That's just an idea off the top of my head, which I think should work. I'm not sure if the `forceUpdate` method of class components is still maintained in React, as I haven't used class components in a while. If you need any assistance getting it set up work correctly, let me know.

**Comment by quisido** [comment]
I've added this to the documentation, so closing this. Thank you for the feedback.
